across:
  development:
    active: true

acrossHibernate:
  hibernate-properties:
    hibernate.format_sql: false
    hibernate.use_sql_comments: false
    hibernate.show_sql: false

applicationInfo:
  environmentId: development

server:
  error:
    includeStacktrace: ALWAYS
  port: 8081

spring:
  datasource:
    url: "jdbc:h2:./local-data/db/client-db"
    username: sa

security:
  oauth2:
    client:
      clientId: demo
      clientSecret: demo
      accessTokenUri: http://localhost:8080/oauth/token
      userAuthorizationUri: http://localhost:8080/oauth/authorize
      authenticationScheme: header
      clientAuthenticationScheme: form
      grant-type: "authorization_code"
      scope: full
      registered-redirect-uri: http://localhost:8080/admin/login
      access-token-validity-seconds: 7200
    sso:
      login-path: "/admin/login"
    resource:
      user-info-uri: http://localhost:8080/me
      token-type: Bearer
      prefer-token-info: false